Feat/221 document search sources string resolver
deepsense-ai/ragbits pull request #264
Opened 2024-12-27 15:16 UTC by maciejklimek

Solves #221

2025-01-02 15:05 UTC, ludwiktrammer requested changes

2025-01-02 15:05 UTC, ludwiktrammer commented on packages/ragbits-document-search/tests/unit/test_document_search.py
> +        await document_search.ingest(f"file://{temp_dir}/test*.txt")
It would be good to test other supported syntax options, for example `file://{temp_dir}/test?.txt`, `file://*.txt`, `file://**/test?.txt`

2025-01-02 15:28 UTC, ludwiktrammer commented
This PR should probably also include some documentation

2025-01-13 08:50 UTC, maciejklimek commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            path_obj = Path.cwd() / path_obj
I'm now using the Resolve method instead of the conditional.

2025-01-16 10:40 UTC, ludwiktrammer commented
@maciejklimek Did you intend to push another commit? Because your comments indicate that you changed things but I don't see the changes here.

2025-01-16 11:22 UTC, maciejklimek commented
> @maciejklimek Did you intend to push another commit? Because your comments indicate that you changed things but I don't see the changes here.

Yeah, sorry for that, but I just really didn't have enough capacity to take care of this.

2025-01-16 12:00 UTC, ludwiktrammer commented
@maciejklimek No problem then :) I just thought that maybe you simply forgot to do a push

2025-01-22 11:52 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
here i think it is justified with nested import issue

2025-01-22 12:16 UTC, ludwiktrammer commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
@kdziedzic68 Can you be more explicit? What do you mean by "nested import issue"?

2025-01-22 12:33 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            # If path contains wildcards, use its parent as base
done, however the one liner mentioned by @ludwiktrammer would not work for absolute paths as absolute patterns are not supported by glob. added clear method to split path into base and pattern

2025-01-22 12:34 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/_main.py
> +            sources = documents  # type: ignore[assignment]
done

2025-01-22 12:34 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/_main.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
removed

2025-01-22 13:18 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
we are importing `ragbits.document_search.documents.source` within ` ragbits.document_search.documents.source_resolver` - if we had imported in in the reversed direction (`ragbits.document_search.documents.source_resolver` within `ragbits.document_search.documents.source`) at the start of the process an error would be thrown

2025-01-22 13:37 UTC, ludwiktrammer commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
So circular imports?

Circular imports are usually indicate a problem with how the code has been structured and should result in thinking about fixing the underlying problem. Seeing two parts of the system you should always be able to tell which one is "upstream" and which one is "downstream".

Even leaving the structural problems aside, nested imports are dangerous because they hide problems with imports (for example, if the import path changes, this will not be checked and reported during initialization - unlike all other imports). It's also less  efficient.

Here the problem is very shallow and fixable. The code itself is structured correctly. The circularity is only due to typing, which can be fixed easily in `document_search/documents/source_resolver.py` by making the import conditional:

```
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ragbits.document_search.documents.sources import Source
```

And replacing all three occurrences of `Source` with `"Source"`

2025-01-22 14:04 UTC, ludwiktrammer commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +class StorageProtocol(Protocol):
I struggle to understand why we need to define a new `StorageProtocol`? We always use the same class here - `Storage` from `gcloud.aio.storage`. Why can't we use it for typing directly?

2025-01-22 14:21 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +class StorageProtocol(Protocol):
i'm not sure - would ask @maciejklimek about that

2025-01-22 14:36 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +        return path, "*"
done

2025-01-22 14:37 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            from ragbits.document_search.documents.source_resolver import SourceResolver
done

2025-01-22 14:41 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +class StorageProtocol(Protocol):
my best guess would be that it could be somehow benefitial if we had wanted to use different clouds than gcp ? however there is assumption of certain interface

2025-01-22 14:46 UTC, kdziedzic68 commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +class StorageProtocol(Protocol):
have messaged Maciek

2025-01-22 15:25 UTC, ludwiktrammer commented on packages/ragbits-document-search/src/ragbits/document_search/documents/sources.py
> +            storage: The storage client to use (in tests, this can be a mock)
```suggestion
            storage: The `gcloud-aio-storage` `Storage` object to use as the storage client.
                By default, the object will be created automatically.
```

2025-01-22 15:32 UTC, merged